baseURL = "https://jorgemht.dev/"

# determines default content language
defaultContentLanguage = "es"

# language code
languageCode = "es"
title = "Jorgemht.dev"

# Change the default theme to be use when building the site with Hugo
theme = "uBlogger"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    title = "Posts"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Etiquetas"
    url = "/tags/"
    title = "Etiquetas"
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false


[params]
  # uBlogger theme version
  version = "1.3.X"
  # site description
  description = "Pagina web dedicada al desarrollo de aplicaciones para el ecosistema de Apple"
  # site keywords
  keywords = ["Swift", "Swift UI"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  #  gitRepo = ""
  # which hash function used for SRI, when empty, no SRI is used
  # ("sha256", "sha384", "sha512", "md5")
  # fingerprint = ""

# date format
  dateFormat = "02 01 2006"

# website images for Open Graph and Twitter Cards
  # images = ["/logo.png"]

# App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    # title = "uBlogger"
    # whether to omit favicon resource links
    # noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    # svgFavicon = ""
    # Android browser theme color
    # themeColor = "#ffffff"
    # Safari mask icon color
    # iconColor = "#5bbad5"
    # Windows v8-10 tile color
    # tileColor = "#da532c"

# Search config
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = "buscar post"
    # max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    # highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    # absoluteURL = false
    # [params.search.algolia]
     #  index = ""
     #  appID = ""
     #  searchKey = ""

# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"

# Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "jorgemht dev"
      # you can add extra information before the name (HTML format is supported), such as icons
      # pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      # post = ""
      
# whether to use typeit animation for title name
     # typeit = false

# Footer config
  [params.footer]
    enable = true
  # Custom content (HTML format is supported)
    # custom = ''
  # whether to show Hugo and theme info
    hugo = false
  # to show copyright info
    copyright = true
  # whether to show the author
    author = true
  # Site creation time
    since = 2021
  # license info (HTML format is supported)
    # license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Section (all posts) page config
  # [params.section]
    # special amount of posts in each section page
     # paginate = 20
    # date format (month and day)
    # dateFormat = "01-02"
    # amount of RSS pages
    # rss = 10

# List (category or tag) page config
# [params.list]
    # special amount of posts in each list page
      # paginate = 20
    # date format (month and day)
      # dateFormat = "01-02"
    # amount of RSS pages
      # rss = 10
    
 # Home page config
  [params.home]
  # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/jorgemht.jpg"
      # title shown in home page (HTML format is supported)
      # title = ""
      # subtitle shown in home page
      subtitle = "Bienvenidos a mi blog"
      # whether to use typeit animation for subtitle
      typeit = true 
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      # disclaimer = ""
    
# Home page posts
    # [params.home.posts]
      # enable = true
      # special amount of posts in each home posts page
      # paginate = 6
      # replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      # defaultHiddenFromHomePage = false

# Social config about the author
  [params.social]
    GitHub = "jorgemhtdev"
    Youtubechannel = "jorgemhtdev"
    Linkedin = "jorgemhtdev"
    Twitter = "jorgemhtdev"

# Page config
  [params.page]
    # main subject for articles, by default classic. more on themes}
    theme = "classic"
    # whether to hide a page from home page
    # hiddenFromHomePage = false
    # whether to hide a page from search results
    # hiddenFromSearch = false
    # Allows you to hide the preview image on the article page
    # hiddenFeaturedImage = false
    # whether to enable twemoji
    # twemoji = false
    # whether to enable lightgallery
    # lightgallery = false
    # whether to enable the ruby extended syntax
    # ruby = true
    # whether to enable the fraction extended syntax
    # fraction = true
    # whether to enable the fontawesome extended syntax
    # fontawesome = true
    # whether to show link to Raw Markdown content of the content
    # linkToMarkdown = true
    # whether to show the full text content in RSS
    # rssFullText = false
    # Post display settings on the page
    # [params.summary]
      # Display previews on the page of posts
      # hiddenImage = false
      # Allows you to hide the description
      # hiddenDescription = false
      # Allows you to hide the title
      # hiddenTitle = false
    # Tag display settings
    # [params.summary.tags]
      # One of the options for displaying tags
      # theme = "image"
      # Text color
      # color = "white"
      # Backing color
      # background = "black"
      # Tag transparency
      transparency = 0.9
    # Fasting time display
    # [params.timeAgo]
      # enable = "false"
      # lang = "en"
    # Table of the contents config
    # [params.page.toc]
      # whether to enable the table of the contents
      # enable = true
      # whether to keep the static table of the contents in front of the post
      # keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      # auto = true
    # KaTeX mathematical formulas
    # [params.page.math]
      # enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      # blockLeftDelimiter = ""
      # blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      # inlineLeftDelimiter = ""
      # inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      # copyTex = true
      # KaTeX extension mhchem
      # mhchem = true
    # Code config
    # [params.page.code]
      # whether to show the copy button of the code block
      # copy = true
      # the maximum number of lines of displayed code by default
      # maxShownLines = 10
    # Mapbox GL JS config
    # [params.page.mapbox]
      # access token of Mapbox GL JS
      # accessToken = ""
      # style for the light theme
      # lightStyle = "mapbox://styles/mapbox/light-v9"
      # style for the dark theme
      # darkStyle = "mapbox://styles/mapbox/dark-v9"
      # whether to add NavigationControl
      # navigation = true
      # whether to add GeolocateControl
      # geolocate = true
      # whether to add ScaleControl
      # scale = true
      # whether to add FullscreenControl
      # fullscreen = true
 
#social share links in post page
  [params.page.share]
    enable = true
      Twitter = true
      Linkedin = true
      Whatsapp = true
      Reddit = true
      Facebook = true
      
#Third-party library config
    #[params.page.library]
      #[params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/"
        # Or
        # someCSS = "https://cdn.example.com/some.css"
      #[params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/"
        # Or
        # someJavascript = "https://cdn.example.com/some.js"
    #Page SEO config
    #[params.page.seo]
      # image URL
      #images = []
      # Publisher info
      #[params.page.seo.publisher]
        #name = ""
        #logoUrl = ""
  
    #Comment config
    #[params.comment]
      #enable = true
      #Remark42 comment config
      #[params.comment.remark42]
        #enable = false
        # the location of your server with Remark42
        #host = "https://remark.example.com"
        # remark42 supports comments for several sites at once, this identifier indicates which site to display comments for.
        #site = "you_site_key"
        # design theme
        #theme = "light"
        # language
        #locale = "en"
        # enable or disable smiley support
        #emailSubscribe = "true"
      # Disqus comment config
      #[params.comment.disqus]
        #enable = false
        #Disqus shortname to use Disqus in posts
        # shortname = ""
      # Gitalk comment config
      # [params.comment.gitalk]
        # enable = false
        # owner = ""
        # repo = ""
        # clientId = ""
        # clientSecret = ""
      # Valine comment config
      # [params.comment.valine]
        # enable = false
        # appId = ""
        # appKey = ""
        # placeholder = ""
        # avatar = "mp"
        # meta= ""
        # pageSize = 10
        # lang = ""
        # visitor = true
        # recordIP = true
        # highlight = true
        # enableQQ = false
        # serverURLs = ""
        # emoji data file name, default is "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # located in "themes/uBlogger/assets/data/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/data/emoji/"
        # emoji = ""
      # Facebook comment config
      # [params.comment.facebook]
        # enable = false
        # width = "100%"
        # numPosts = 10
        # appId = ""
        # languageCode = ""
      # Telegram comments config
      # [params.comment.telegram]
        # enable = false
        # siteID = ""
        # limit = 5
        # height = ""
        # color = ""
        # colorful = true
        # dislikes = false
        # outlined = false
      # Commento comment config
      # [params.comment.commento]
        # enable = false
      # Utterances comment config
      # [params.comment.utterances]
        # enable = false
        # owner/repo
        # repo = ""
        # issueTerm = "pathname"
        # label = ""
        # lightTheme = "github-light"
        # darkTheme = "github-dark"

  # TypeIt config
   # [params.typeit]
    # typing speed between each step (measured in milliseconds)
     # speed = 100
    # blinking speed of the cursor (measured in milliseconds)
     # cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
     # cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
     # duration = -1
  # Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
   # [params.verification]
     # google = ""
     # bing = ""
     # yandex = ""
     # pinterest = ""
     # baidu = ""
  # Site SEO config
   # [params.seo]
    # image URL
     # image = ""
    # thumbnail URL
     # thumbnailUrl = ""

  # Analytics config
   # [params.analytics]
     # enable = false
    # Google Analytics
     # [params.analytics.google]
       # id = ""
      # whether to anonymize IP
       # anonymizeIP = true
    # Fathom Analytics
     # [params.analytics.fathom]
       # id = ""
      # server url for your tracker if you're self hosting
       # server = ""
    # Yandex.Metrika
     # [params.analytics.yandex]
      # your meter number
       # id = ""
  # Cookie consent config
   # [params.cookieconsent]
     # enable = true
    # text strings used for Cookie consent banner
     # [params.cookieconsent.content]
       # message = ""
       # dismiss = ""
       # link = ""
  # CDN config for third-party library files
   # [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/uBlogger/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
     # data = ""
  # Compatibility config
   # [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
     # polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
     # objectFit = false

# Markup related config in Hugo
 # [markup]
  # Syntax Highlighting
   # [markup.highlight]
     # codeFences = true
     # guessSyntax = true
     # lineNos = true
     # lineNumbersInTable = true
    # false is a necessary configuration
     # noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
   # [markup.goldmark]
     # [markup.goldmark.extensions]
       # definitionList = true
       # footnote = true
       # linkify = true
       # strikethrough = true
       # table = true
       # taskList = true
       # typographer = true
     # [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
       # unsafe = true
  # Table Of Contents settings
   # [markup.tableOfContents]
     # startLevel = 2
     # endLevel = 6

# Author config
# [author]
  # name = "xxxx"

# Sitemap config
# [sitemap]
  # changefreq = "weekly"
  # filename = "sitemap.xml"
  # priority = 0.5

# Permalinks config
# [Permalinks]
  # posts = ":year/:month/:filename"
  # posts = ":filename"

# Privacy config
# [privacy]
  # privacy of the Google Analytics (replaced by params.analytics.google)
  # [privacy.googleAnalytics]
    # ...
  # [privacy.twitter]
    # enableDNT = true
  # [privacy.youtube]
    # privacyEnhanced = true

# Options to make output .md files
# [mediaTypes]
  # [mediaTypes."text/plain"]
    # suffixes = ["md"]

# Options to make output .md files
# [outputFormats.MarkDown]
  # mediaType = "text/plain"
  # isPlainText = true
  # isHTML = false

# Options to make hugo output files
# [outputs]
  # home = ["HTML", "RSS", "JSON"]
  # page = ["HTML", "MarkDown"]
  # section = ["HTML", "RSS"]
  # taxonomy = ["HTML", "RSS"]
  # taxonomyTerm = ["HTML"]